import { describe, expect, it } from "vitest";

// The validation regex used in Fastify startup check and PM2 configuration
const DB_BACKUP_PASSWORD_REGEX = /^[0-9a-fA-F]{64}$/;

describe("DB_BACKUP_PASSWORD validation regex", () => {
  it("approves valid 64-character hex strings generated by openssl rand -hex 32", () => {
    // Exactly 64 hex characters (32 bytes)
    const validPassword1 = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08";
    const validPassword2 = "a9a1332e9fc5e0b44f44b4c71b07847ec7c20d72000000000000000000000000";
    const validPasswordUpper = "9F86D081884C7D659A2FEAA0C55AD015A3BF4F1B2B0B822CD15D6C15B0F00A08";

    expect(DB_BACKUP_PASSWORD_REGEX.test(validPassword1)).toBe(true);
    expect(DB_BACKUP_PASSWORD_REGEX.test(validPassword2)).toBe(true);
    expect(DB_BACKUP_PASSWORD_REGEX.test(validPasswordUpper)).toBe(true);
  });

  it("rejects shorter hex strings", () => {
    // 32-character hex (16 bytes, e.g. openssl rand -hex 16)
    const invalidShort = "9f86d081884c7d659a2feaa0c55ad015";
    expect(DB_BACKUP_PASSWORD_REGEX.test(invalidShort)).toBe(false);
  });

  it("rejects longer hex strings", () => {
    // 66-character hex
    const invalidLong = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08aa";
    expect(DB_BACKUP_PASSWORD_REGEX.test(invalidLong)).toBe(false);
  });

  it("rejects non-hex characters", () => {
    // 64 characters but contains 'g'
    const invalidChars = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a0g";
    expect(DB_BACKUP_PASSWORD_REGEX.test(invalidChars)).toBe(false);
  });

  it("rejects empty strings", () => {
    expect(DB_BACKUP_PASSWORD_REGEX.test("")).toBe(false);
  });
});
