const fs = require('fs');
const path = require('path');

function parseDotEnv(filePath) {
  const env = {};
  if (!fs.existsSync(filePath)) return env;
  const content = fs.readFileSync(filePath, 'utf8');
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const splitIndex = trimmed.indexOf('=');
    if (splitIndex === -1) return;
    const key = trimmed.slice(0, splitIndex).trim();
    let val = trimmed.slice(splitIndex + 1).trim();
    if (val.length >= 2 && ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'")))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  });
  return env;
}

const projectRoot = __dirname;
const fileEnv = parseDotEnv(path.join(projectRoot, '.env'));
const mergedEnv = {
  ...fileEnv,
  ...process.env,
};

const finalEnv = {
  NODE_ENV: mergedEnv.NODE_ENV || 'production',
  HOST: mergedEnv.HOST || '127.0.0.1',
  PORT: mergedEnv.PORT || '3000',
  DB_FILE: mergedEnv.DB_FILE || path.join(projectRoot, 'data/promptgate.sqlite'),
  PROMPTGATE_SECRET: mergedEnv.PROMPTGATE_SECRET,
  DB_BACKUP_PASSWORD: mergedEnv.DB_BACKUP_PASSWORD,
  LOG_LEVEL: mergedEnv.LOG_LEVEL || 'info',
  NODE_INTERPRETER: mergedEnv.NODE_INTERPRETER,
};

if (finalEnv.NODE_ENV === 'production' && !finalEnv.PROMPTGATE_SECRET) {
  throw new Error('PROMPTGATE_SECRET is required in production. Please configure it in .env.');
}

if (finalEnv.DB_BACKUP_PASSWORD && (finalEnv.DB_BACKUP_PASSWORD.length !== 64 || !/^[0-9a-fA-F]+$/.test(finalEnv.DB_BACKUP_PASSWORD))) {
  throw new Error('DB_BACKUP_PASSWORD must be a 64-character hex string (generated by openssl rand -hex 32).');
}

module.exports = {
  apps: [
    {
      name: 'promptgate-server',
      script: 'apps/server/dist/index.js',
      node_args: '-r ./apps/server/preload.js',
      interpreter: finalEnv.NODE_INTERPRETER,
      cwd: projectRoot,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: finalEnv
    }
  ]
};
