packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  es5-ext: true
  esbuild: true
  msw: true
  protobufjs: set this to true or false
  sharp: set this to true or false
allowedDeprecatedVersions:
  "@esbuild-kit/core-utils": "*"
  "@esbuild-kit/esm-loader": "*"
  "node-domexception": "*"
  "prebuild-install": "*"
