packages:
  - "apps/*"
  - "packages/*"
dangerouslyAllowAllBuilds: true
allowBuilds:
  "@google/genai": true
  argon2: true
  better-sqlite3: true
  es5-ext: true
  esbuild: true
  msw: true
  protobufjs: true
  puppeteer: true
  sharp: true
allowedDeprecatedVersions:
  "@esbuild-kit/core-utils": "*"
  "@esbuild-kit/esm-loader": "*"
  "node-domexception": "*"
  "prebuild-install": "*"
