import "./polyfill";
import Fastify from "fastify";
import cookie from "@fastify/cookie";
import jwt from "@fastify/jwt";
import { bootstrap, isMigrationCompleted } from "./bootstrap";
import dotenv from "dotenv";
import crypto from "crypto";
import "./services/chatLogService";
import { scheduleDingTalkJobs } from "./services/dingtalk";
import { scheduleDistillationJobs } from "./services/distillation/scheduler";
import { scheduleOpencodeAutoUpdate } from "./opencode/autoUpdate";
import { logAction } from "./utils/actionLogger";

const envPath = process.cwd().endsWith("server") ? "../../.env" : ".env";
dotenv.config({ path: envPath });

const port = Number(process.env.PORT) || 3000;
const host = process.env.HOST || "127.0.0.1";
let secret = process.env.PROMPTGATE_SECRET;

if (!secret) {
  if (process.env.NODE_ENV === "production") {
    console.error("ERROR: PROMPTGATE_SECRET is required in production.");
    process.exit(1);
  } else {
    console.warn(
      "WARN: PROMPTGATE_SECRET is not set. Generating a temporary secret for development.",
    );
    secret = crypto.randomBytes(32).toString("hex");
  }
}

const backupPassword = process.env.DB_BACKUP_PASSWORD;
if (backupPassword) {
  const isHex64 = /^[0-9a-fA-F]{64}$/.test(backupPassword);
  if (!isHex64) {
    console.error("ERROR: DB_BACKUP_PASSWORD must be a 64-character hex string (generated by openssl rand -hex 32).");
    process.exit(1);
  }
}

const fastify = Fastify({
  logger: {
    level: process.env.NODE_ENV === "production" ? "info" : "debug",
    transport: {
      target: "pino-pretty",
    },
  },
  trustProxy: true,
  bodyLimit: 1073741824, // 1GB — gateway should not restrict; let upstream LLM decide
});

// Gracefully handle empty JSON bodies (e.g. for DELETE requests)
const defaultJsonParser = fastify.getDefaultJsonParser("error", "error");
fastify.addContentTypeParser(
  "application/json",
  { parseAs: "string" },
  (request, body, done) => {
    if (body === "" || body == null) {
      return done(null, {});
    }
    return defaultJsonParser(request, body as string, done);
  }
);

import { db, initDb } from "./db";
import { systemSettings } from "./db/schema";
import { eq } from "drizzle-orm";
import {
  isFreshInstall,
  hasUnattendedEnv,
  performUnattendedSetup,
  getSetupPending,
  setSetupPending,
} from "./services/setup";
import setupRoutes from "./routes/setup";
import {
  ERR_SETUP_REQUIRED,
  ERR_SETUP_REQUIRED_MESSAGE,
  ERR_MAINTENANCE_ACTIVE,
  ERR_MAINTENANCE_ACTIVE_MESSAGE,
} from "@promptgate/shared";
import {
  isMaintenanceMode,
  incrementInFlight,
  decrementInFlight,
} from "./services/maintenance";

// We manage CORS manually via hooks for dynamic origin allowing
fastify.addHook("onRequest", async (request, reply) => {
  incrementInFlight();

  // Maintenance mode gate per PRD §9.2
  if (isMaintenanceMode()) {
    const url = request.url.split("?")[0];
    if (url.startsWith("/v1/") || url.startsWith("/v0/")) {
      return reply
        .header("Retry-After", "30")
        .code(503)
        .send({
          error: {
            message: ERR_MAINTENANCE_ACTIVE_MESSAGE,
            type: "maintenance_active",
            code: ERR_MAINTENANCE_ACTIVE,
          },
        });
    }
    // Block mutating admin requests except database migration / status endpoints
    if (
      request.method !== "GET" &&
      request.method !== "HEAD" &&
      request.method !== "OPTIONS"
    ) {
      if (!url.startsWith("/api/settings/database")) {
        return reply.code(503).send({
          error: "System maintenance in progress",
          code: ERR_MAINTENANCE_ACTIVE,
          message: ERR_MAINTENANCE_ACTIVE_MESSAGE,
        });
      }
    }
  }

  const origin = request.headers.origin;
  if (origin) {
    try {
      const settings = await db
        .select()
        .from(systemSettings)
        .where(eq(systemSettings.key, "corsAllowlist"));
      const allowlistStr =
        settings.length > 0
          ? settings[0].value
          : process.env.NODE_ENV === "production"
            ? "[]"
            : '["*"]';

      const mainDomainSettings = await db
        .select()
        .from(systemSettings)
        .where(eq(systemSettings.key, "mainDomain"));
      const mainDomain =
        mainDomainSettings.length > 0 ? mainDomainSettings[0].value : "";

      const allowlist: string[] = JSON.parse(allowlistStr);

      if (process.env.NODE_ENV === "production") {
        // Production: NEVER allow ["*"] + credentials.
        // If allowlist contains "*", fall back to mainDomain-only matching.
        let isAllowed = false;

        if (allowlist.includes("*")) {
          // Wildcard in prod: only allow same-site (mainDomain and its subdomains)
          if (mainDomain) {
            try {
              const originHost = new URL(origin).hostname;
              isAllowed =
                originHost === mainDomain ||
                originHost.endsWith(`.${mainDomain}`);
            } catch {
              isAllowed = false;
            }
          }
          // If no mainDomain configured, nothing is allowed
        } else {
          // Explicit allowlist: exact match only
          isAllowed = allowlist.includes(origin);
        }

        if (isAllowed) {
          reply.header("Access-Control-Allow-Origin", origin);
          reply.header("Access-Control-Allow-Credentials", "true");
        }
        // If not allowed, no CORS headers = browser blocks the request
      } else {
        // Development: allow wildcard (no credentials reflection needed for dev)
        if (allowlist.includes("*")) {
          reply.header("Access-Control-Allow-Origin", origin);
          reply.header("Access-Control-Allow-Credentials", "true");
        } else if (allowlist.includes(origin)) {
          reply.header("Access-Control-Allow-Origin", origin);
          reply.header("Access-Control-Allow-Credentials", "true");
        }
      }
    } catch (e) {
      // DB not ready yet (bootstrap phase) — allow in dev only
      if (process.env.NODE_ENV !== "production") {
        reply.header("Access-Control-Allow-Origin", origin);
        reply.header("Access-Control-Allow-Credentials", "true");
      }
    }
  }

  // Handle preflight
  if (request.method === "OPTIONS") {
    reply.header(
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE, OPTIONS",
    );
    reply.header(
      "Access-Control-Allow-Headers",
      "Origin, Content-Type, Accept, Authorization, x-api-key, x-anthropic-client, anthropic-version, x-backup-password",
    );
    return reply.send();
  }

  // Setup pending gate
  if (getSetupPending()) {
    const url = request.url.split("?")[0];

    // Always allow setup APIs, health check, setup UI, and static assets
    if (
      url.startsWith("/api/setup") ||
      url === "/api/health" ||
      url.startsWith("/assets/") ||
      url === "/setup" ||
      url === "/favicon.ico"
    ) {
      return;
    }

    // Gateway /v1/* returns clear uninitialized error from packages/shared
    if (url.startsWith("/v1/")) {
      return reply.code(503).send({
        error: {
          message: ERR_SETUP_REQUIRED_MESSAGE,
          type: "uninitialized_error",
          code: ERR_SETUP_REQUIRED,
        },
      });
    }

    // Console and auth routes redirect to /setup with 307
    if (
      url === "/login" ||
      url === "/console" ||
      url === "/admin" ||
      url.startsWith("/api/auth")
    ) {
      return reply.code(307).redirect("/setup");
    }

    // Other API requests return 503
    if (url.startsWith("/api/")) {
      return reply.code(503).send({
        error: "Setup required",
        code: ERR_SETUP_REQUIRED,
        message: ERR_SETUP_REQUIRED_MESSAGE,
      });
    }
  }
});

fastify.addHook("onResponse", async () => {
  decrementInFlight();
});

fastify.register(cookie);
fastify.register(jwt, {
  secret: secret,
  cookie: {
    cookieName: "token",
    signed: false,
  },
});

import authRoutes from "./routes/auth";
import apiKeyRoutes from "./routes/apiKeys";
import providerRoutes from "./routes/providers";
import subdomainRoutes from "./routes/subdomains";
import endpointRoutes from "./routes/endpoints";
import policyRoutes from "./routes/policies";
import gatewayRoutes from "./routes/gateway";
import usageRoutes from "./routes/usage";
import settingsRoutes from "./routes/settings";
import userRoutes from "./routes/users";
import inviteCodeRoutes from "./routes/inviteCodes";
import dashboardRoutes from "./routes/dashboard";
import analyticsRoutes from "./routes/analytics";
import logsRoutes from "./routes/logs";
import unifiedRoutes from "./routes/routes";
import eventsRoutes from "./routes/events";
import groupsRoutes from "./routes/groups";
import openapiRoutes from "./routes/openapi";
import chatLogsRoutes from "./routes/chatLogs";
import cacheRoutes from "./routes/cache";
import distillationRoutes from "./routes/distillation";
import { opencodeRoutes } from "./opencode";
import { registerAdminSpaServing } from "./utils/adminSpaServing";

fastify.get("/api/health", async () => {
  return { status: "ok" };
});

fastify.register(authRoutes);
fastify.register(apiKeyRoutes);
fastify.register(providerRoutes);
fastify.register(subdomainRoutes);
fastify.register(endpointRoutes);
fastify.register(policyRoutes);
fastify.register(gatewayRoutes);
fastify.register(opencodeRoutes);
fastify.register(usageRoutes);
fastify.register(settingsRoutes);
fastify.register(userRoutes);
fastify.register(inviteCodeRoutes);
fastify.register(dashboardRoutes);
fastify.register(analyticsRoutes);
fastify.register(logsRoutes);
fastify.register(chatLogsRoutes);
fastify.register(cacheRoutes);
fastify.register(distillationRoutes);
fastify.register(unifiedRoutes);
fastify.register(eventsRoutes);
fastify.register(groupsRoutes);
fastify.register(openapiRoutes);
fastify.register(setupRoutes);

registerAdminSpaServing(fastify);

const start = async () => {
  try {
    await initDb();

    const isPrimary =
      !process.env.NODE_APP_INSTANCE || process.env.NODE_APP_INSTANCE === "0";

    const fresh = await isFreshInstall();

    if (fresh) {
      if (hasUnattendedEnv()) {
        console.log(
          "[PromptGate Bootstrap] Unattended setup environment detected. Initializing system...",
        );
        await performUnattendedSetup();
        setSetupPending(false);
        if (isPrimary) {
          await bootstrap();
        }
      } else {
        setSetupPending(true);
        console.log(
          "[PromptGate] Fresh installation detected. Setup wizard is required.",
        );
        console.log(
          `[PromptGate] Open http://${host}:${port}/setup to finish installation.`,
        );
      }
    } else {
      setSetupPending(false);
      if (isPrimary) {
        await bootstrap();
      } else {
        // Poll and wait for primary instance to complete migrations
        let migrated = false;
        for (let i = 0; i < 15; i++) {
          migrated = await isMigrationCompleted();
          if (migrated) break;
          await new Promise((resolve) => setTimeout(resolve, 1000));
        }
        if (!migrated) {
          throw new Error(
            "Database migrations did not complete on primary instance within timeout.",
          );
        }
      }
    }

    await fastify.listen({ port, host });
    fastify.log.info(`Server listening on ${host}:${port}`);

    if (isPrimary && !getSetupPending()) {
      logAction({
        level: "INFO",
        code: "system.started",
        host,
        port,
        env: process.env.NODE_ENV || "development",
      });

      await scheduleDingTalkJobs();
      await scheduleDistillationJobs();
      await scheduleOpencodeAutoUpdate();
    }
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
